### ISSUE TITLE
Login OTP 

### ISSUE THREAD

**Issue by tcmhoang** [Revup-vn/revup-flutter-app-consumer#44]
Dear Mr. Huy Senior, Flutter Pro Dinkao @wamynobe ,

In version 3.0+ of the core package, an unregistered user needs to get the video call account before finishing registration in the app. I also need to get the FCM token to receive the notification.

Regarding your re-verification OTP concerns, you need to use the `onTimeOut` callback in the `LoginWithPhone` event to re-verification OTP if the user types a wrong code. If you need that feature :)

You need to act asap. We don't have much time.

Your kohai,
🙇

**Comment by wamynobe** [comment]
got it sensei

**Comment by wamynobe** [comment]
done nhe kohai tuan =))
